version: '2.4'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: liquibase
      POSTGRES_PASSWORD: liquibase
      POSTGRES_DB: liquibase
    ports:
      - '5432:5432'
    expose:
      - '5432'
